### ISSUE TITLE
Hardcoding of file path of "sd-messages.h" preventing using this in build systems

### ISSUE THREAD

**Issue by mpoornima** [systemd/python-systemd#23]
Hi,

We are trying to build python-systemd for a different architecture using yocto build system, but due to the hardcoding of the file path of ```sd-messages.h``` in ```setup.py``` we are unable to do so unless the systemd header files are installed on the build system and are of the same version as that of the target build

Offending lines:
~~~~
constants = [line.split()[1]
                         for line in open("/usr/include/systemd/sd-messages.h")
                         if line.startswith('#define SD_MESSAGE_')]
~~~~

The code should instead take a relative path to systemd headers and use that instead of the absolute path. Will send you out a pull request for the same if it is acceptable or please suggest an alternative.

**Comment by keszybz** [comment]
Yes, sure, making this relative to systemd headers sounds reasonable. It was fixed before because that's where it ends up on most systems, so there was no good reason to make this configurable.

**Comment by christophgysin** [comment]
I've been having the same issue, and fixed it by making setup.py respect the SYSROOT environment variable if set. Please see #25 and consider applying.

Thanks!

**Comment by keszybz** [comment]
Sorry for the long delay in reviewing this.

Unfortunately neither #24 not #25 really solve the problem. setup.py uses the pkg-config file to determine libsystemd version, so just overriding the location of the header file might result in a build which does  not provide full functionality / is broken.

I added https://github.com/keszybz/python-systemd/commit/7fa20172d5942dc7397de3802abe4474968ff8f0, which makes setup.py look for the header file based on the pkg-config file. Does that work for you?

**Comment by christophgysin** [comment]
I'm afraid that does not solve the problem. libsystemd.pc is not aware that it was installed into a different root, and its includedir is still pointing to /usr/include.

But pkg-config is correctly finding the correct version of libsystemd, because cross-compile environments will override the path to pkg-config and PKG_CONFIG_PATH to point to the correct *.pc files. So #25 does fix the problem, provided that the cross-compile environment specifies the correct path to the sysroot with the SYSROOT variable.
